Repository purduesigbots/pros-docs, pull requests merged in 2020-11, with the labels that each got.

#200 Rotation/Optical Page Fixes
  v5/api/c/optical.rst
  v5/api/c/rotation.rst
  v5/api/cpp/optical.rst
  v5/api/cpp/rotation.rst
Labels: Priority: High, Type: Bug

#201 Infinite While Loops in Initialize Fix
  v5/api/api-legacy.rst
  v5/api/c/llemu.rst
  v5/api/cpp/imu.rst
  v5/api/cpp/llemu.rst
  v5/tutorials/topical/adi.rst
  v5/tutorials/topical/llemu.rst
Labels: bug

#202 Motor Functions not Respecting Brake Mode
  v5/api/c/motors.rst
  v5/api/cpp/motors.rst
Labels: enhancement

#195 Add instructions for the Vision Utility on Linux
  v5/getting-started/linux.rst
Labels: enhancement
